WeTogetherYamal/src/WeTogetherYamal.App/Controllers/EventsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WeTogetherYamal.SharedKernel.Models.EventRequest;

namespace WeTogetherYamal.Api.Controllers
{
    [Route("/[controller]")]
    public class EventsController : Controller
    {
        [AllowAnonymous]
        [HttpGet("memoryBookYamal")]
        public IActionResult MemoryBookYamal()
        {
            return GetPageWithSubmitForm();
        }

        [AllowAnonymous]
        [HttpGet("storyRunsThroughHouse")]
        public IActionResult StoryRunsThroughHouse()
        {
            return GetPageWithSubmitForm();
        }
        
        [AllowAnonymous]
        [HttpGet("victoryScarf")]
        public IActionResult VictoryScarf()
        {
            return GetPageWithSubmitForm();
        }

        [AllowAnonymous]
        [HttpGet("warLetters")]
        public IActionResult WarLetters()
        {
            return GetPageWithSubmitForm();
        }

        [AllowAnonymous]
        [HttpGet("weRemember")]
        public IActionResult WeRemember()
        {
            return GetPageWithSubmitForm();
        }

        private IActionResult GetPageWithSubmitForm()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("GetEventRequestList", "AdminPanel");
            }
            var model = new CreateEventRequestViewModel();
            return View(model);
        }
    }
}

WeTogetherYamal/src/WeTogetherYamal.App/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WeTogetherYamal.Api.Controllers
{
    [Route("/[controller]")]
    public class GalleryController : Controller
    {
        [AllowAnonymous]
        [HttpGet("memoryBookYamal")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

WeTogetherYamal/src/WeTogetherYamal.App/Controllers/MainPageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WeTogetherYamal.Core.Interfaces;
using WeTogetherYamal.SharedKernel.Models.EventRequest;

namespace WeTogetherYamal.Api.Controllers
{
    [Route("/")]
    public class MainPageController : Controller
    {
        private readonly ICoreEventRequestService _eventRequestService;

        public MainPageController(ICoreEventRequestService eventRequestService)
        {
            _eventRequestService = eventRequestService ?? throw new ArgumentNullException(nameof(eventRequestService));
        }

        // GET: MainPageController
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("GetEventRequestList", "AdminPanel");
            }
            var model = new CreateEventRequestViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(CreateEventRequestViewModel model)
        {
            if (model == null || !ModelState.IsValid)
            {
                ViewData["ModelIsValid"] = false;
                return View(model);
            }

            await _eventRequestService.CreateEventRequestAsync(model);
            var returnUrl = model.ReturnUrl ?? "/";
            return Redirect(returnUrl);
        }
    }
}

WeTogetherYamal/src/WeTogetherYamal.App/Views/Shared/CitiesCards.cshtml
<DIV class="container">
    <div class="action" style="margin-top: 0px;">
        <div class="action__title ">
            <h2>Альбомы городов</h2>
        </div>
        <div class="action__items ">
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Aksarka.png" alt="">
                    <div class="card__title">Аксарка</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Gubkinskii.png" alt="">
                    <div class="card__title">Губкинский</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Labintangi.png" alt="">
                    <div class="card__title">Лабытнанги</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Muravlenko.png" alt="">
                    <div class="card__title">Муравленко</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Nadim.png" alt="">
                    <div class="card__title">Надым</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Noyabrsk.png" alt="">
                    <div class="card__title">Ноябрьск</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Salehard.png" alt="">
                    <div class="card__title">Салехард</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Tazovski.png" alt="">
                    <div class="card__title">Тазовский</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/TarkoSale.png" alt="">
                    <div class="card__title">Тарко-Сале</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
            <a asp-action="Index" asp-controller="Gallery">
                <div class="action__items-card card col-3"><img src="~/img/Hanmei.png" alt="">
                    <div class="card__title">Ханымей</div>
                    <div class="card__text">посмотреть</div>
                </div>
            </a>
        </div>
    </div>
</DIV>

WeTogetherYamal/src/WeTogetherYamal.App/Views/Shared/Footer.cshtml
<footer>
    <div class="container">
        <div class="footer row flex-xl-wrap">
            <div class="footer__museums col-lg-5">
                <div class="footer__title">Музеи</div>
                <ul class="footer__list list">
                    <li class="list-item">МБУ Губкинский музей освоения Севера </li>
                    <li class="list-item">МБУК Ханымейский историко-краеведческий музей</li>
                    <li class="list-item">МАУК Городской краеведческий музей</li>
                    <li class="list-item">ГБУ Ямало-Ненецкий окружной музейно-выставочный комплекс имени И.С.
                        Шемановского</li>
                </ul>
            </div>
            <div class="footer__contacts col-lg-3">
                <div class="footer__title">Контакты</div>
                <ul class="footer__list list">
                    <li class="list-item">vk.com/pobedavnesteyamal</li>
                    <li class="list-item">@@pobedavmesteyamal</li>
                    <li class="list-item">ok.ru/pobedavmesteyamal</li>
                    <li class="list-item">museum-noyabrsk@yandex.ru</li>
                </ul>
            </div>
        </div>
    </div>
</footer>

WeTogetherYamal/src/WeTogetherYamal.App/Views/Shared/Header.cshtml
@using LamarCodeGeneration.Frames
<header>
    <div class="header__up">
        <div class="container ">
            <h1>#ПобедаВместеЯмал</h1>
        </div>
    </div>
    <nav class="header__down navbar navbar-expand-xl header-bg">
        <a class="navbar-brand header__brand" asp-action="Index" asp-controller="MainPage">
            <img src="~/img/logo.png" width="100" height="100"
                class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-dark navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-dark navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <div class="container">
                <ul class="navbar-nav justify-content-center">
                    <li class="nav-item" style="padding-left: 0px;">
                        <a class="nav-link menu__item" aria-current="page" asp-action="MemoryBookYamal" asp-controller="Events">Книга памяти Ямал</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link menu__item" asp-action="StoryRunsThroughHouse" asp-controller="Events">История проходит через дом</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link menu__item" asp-action="VictoryScarf" asp-controller="Events">Шарф Победы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link menu__item" asp-action="WarLetters" asp-controller="Events">Письма войны</a>
                    </li>
                    <li class="nav-item" style="padding-right: 0px;">
                        <a class="nav-link menu__item" asp-action="WeRemember" asp-controller="Events">Мы помним</a>
                    </li>
                    @{
                        if (ViewContext.RouteData.Values.Values.Any(x => x.ToString() == "AdminPanel"))
                        {
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item row justify-content-center mb-3 mt-3">
                                    <button class="main-button">
                                        <a class="menu__item" href="@Url.Action("Logout", "AdminPanel")">Выйти</a>
                                    </button>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item row justify-content-center mb-3 mt-3">
                                    <button class="main-button" data-toggle="modal" data-target="#ModalLogin">
                                        <span>Войти в систему</span>
                                    </button>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item row justify-content-center mb-3 mt-3">
                                <button class="main-button" data-toggle="modal" data-target="#ModalForm">
                                    <span>Принять участие</span>
                                </button>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

WeTogetherYamal/src/WeTogetherYamal.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/submitForm.css">

    <title>@ViewData["Title"] - ПобедаВместеЯмал</title>
</head>

<body>
<div class="wrapper">
    @await Html.PartialAsync("Header")
    <main role="main">
        @RenderBody()
    </main>
    @await Html.PartialAsync("Footer")
</div>

<script type="text/javascript" src="~/js/main.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>